# Generated by Django 2.2.24 on 2022-10-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_flat_new_building"),
    ]

    operations = []
