# Generated by Django 2.2.24 on 2022-10-08 13:53

from django.db import migrations
from django.db.backends.sqlite3.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def init_new_buildings(apps: StateApps, schema_editor: DatabaseSchemaEditor):
    flat_model = apps.get_model("property", "Flat")
    for flat in flat_model.objects.all():
        flat.new_building = False
        if flat.construction_year >= 2015:
            flat.new_building = True
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_auto_20221008_1646"),
    ]

    operations = [migrations.RunPython(init_new_buildings)]
