# Generated by Django 2.2.24 on 2022-10-08 13:53

from django.db import migrations
from django.db.backends.sqlite3.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def init_new_buildings(apps: StateApps, schema_editor: DatabaseSchemaEditor):
    flat_model = apps.get_model("property", "Flat")
    flat_model.objects.filter(construction_year__gte=2015).update(new_building=True)
    flat_model.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_auto_20221008_1646"),
    ]

    operations = [migrations.RunPython(init_new_buildings)]
