# Generated by Django 4.1.2 on 2022-10-08 14:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_flat_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="owner_pure_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="has_balcony",
            field=models.BooleanField(db_index=True, verbose_name="Наличие балкона"),
        ),
    ]
