# Generated by Django 4.1.2 on 2022-10-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0012_auto_20221008_2006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="fio",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="ФИО владельца"
            ),
        ),
    ]
