# Generated by Django 4.1.2 on 2022-10-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0013_alter_owner_fio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="flats",
        ),
        migrations.AddField(
            model_name="flat",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                related_name="flats_own",
                to="property.owner",
                verbose_name="Собственники квартиры:",
            ),
        ),
    ]
