# Generated by Django 4.1.2 on 2022-10-08 18:18

from django.db import migrations
from django.db.backends.sqlite3.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def add_flats(apps: StateApps, schema_editor: DatabaseSchemaEditor):
    flat_model = apps.get_model("property", "Flat")
    owner_model = apps.get_model("property", "Owner")
    for flat in flat_model.objects.all().iterator():
        current_owner = owner_model.objects.get(
            fio=flat.owner,
            owners_phonenumber=flat.phonenumber,
            owner_pure_phone=flat.pure_phone,
        )
        flat.owners.add(current_owner)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0014_remove_owner_flats_flat_owners"),
    ]

    operations = [migrations.RunPython(add_flats)]
