# Generated by Django 4.1.2 on 2022-10-11 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0016_remove_flat_owner_remove_flat_owner_pure_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owner",
            old_name="owners_phonenumber",
            new_name="phonenumber",
        ),
        migrations.RenameField(
            model_name="owner",
            old_name="owner_pure_phone",
            new_name="pure_phone",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель жалобы",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="target_flat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="property.flat",
                verbose_name="Целевая квартира",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_flats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто лайкнул:",
            ),
        ),
    ]
